name: Github release

on:
  push:
    branches:
      - main

jobs:
  release:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Create release if unreleased tag is found
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          LATEST_TAG="$(git describe --tags --abbrev=0)"
          if [ ! $(gh release view "$LATEST_TAG" > /dev/null 2>&1) ] ; then
            gh release create "$LATEST_TAG" --fail-on-no-commits --generate-notes
          fi